extends RefCounted

# 검증용 임시 밸런스. 지역 특산품/역사적 기술 보유를 지정하지 않습니다.
# raw_resource -> basic_material -> manufactured_good 분류로 확장합니다.
const ITEM_CATEGORIES: Dictionary = {
	"raw_resource": "원자원", "basic_material": "기초 소재", "manufactured_good": "제조품",
	"staple": "기본물자", "livestock": "목축자원", "regional_specialty": "지역특산",
}
const CATALOG_SOURCE: String = "Samhan660_Trade_Production_Plan_v01.xlsx"
# 엑셀에서 옮긴 검토 자료입니다. 외부 원문 재검증/도시 배치 확정을 뜻하지 않습니다.
# economic_use/military_use는 역할 설명이며 자동 효과나 생산 활성 조건이 아닙니다.
const PRODUCTION_METHODS: Dictionary = {
	"regional_production": "지역생산", "regional_processing": "지역가공",
	"manufacturing": "제조", "gathering": "채집",
}
# 무기는 기존 sword 하나에 저장합니다. weapons는 조회용 별칭이며 별도 품목/장부가 아닙니다.
const ITEM_ALIASES: Dictionary = {"weapons": "sword"}
const SOURCES: Dictionary = {
	"S01": {
		"institution": "국사편찬위원회",
		"title": "철정",
		"period": "삼한~삼국 / 일부 후대 기록",
		"workbook_summary": "철 소재·제철·금속제품과 유통의 근거. 김해·부산의 철정 출토와 경주 황성동 제철유적 소개.",
		"limitation": "7세기 도시별 광산 매장량·생산량을 증명하지 않음. 출토와 채굴을 구분.",
		"url": "https://contents.history.go.kr/mobile/kc/view.do?code=kc_age_10&levelId=kc_r101450",
		"kind": "historical_reference",
		"independently_verified": false,
		"workbook_range": "출처!A5:G5",
	},
	"S02": {
		"institution": "국사편찬위원회",
		"title": "자염과 천일염",
		"period": "삼국~근현대가 함께 서술됨",
		"workbook_summary": "삼국시대 소금 생산·거래 기록을 소개.",
		"limitation": "현대 천일염 시설을 7세기에 소급하지 않음. 개별 염장 위치는 별도 조사.",
		"url": "https://contents.history.go.kr/mobile/km/view.do?levelId=km_012_0070_0030_0020",
		"kind": "historical_reference",
		"independently_verified": false,
		"workbook_range": "출처!A6:G6",
	},
	"S03": {
		"institution": "국사편찬위원회",
		"title": "고대의 경제 생활",
		"period": "삼국 / 통일신라 / 발해 혼재",
		"workbook_summary": "삼국 수출품으로 마직물·인삼·모피·세공품, 수입품으로 비단 등을 제시.",
		"limitation": "후대 발해·울산 이슬람 상인 사례는 632~670년 배치 근거로 사용하지 않음.",
		"url": "https://contents.history.go.kr/front/ta/view.do?levelId=ta_h61_0040_0030_0020",
		"kind": "historical_reference",
		"independently_verified": false,
		"workbook_range": "출처!A7:G7",
	},
	"S04": {
		"institution": "Royal Botanic Gardens, Kew",
		"title": "Panax ginseng",
		"period": "현대 식물 분포 자료",
		"workbook_summary": "인삼 자생 범위를 러시아 극동~한국으로 설명.",
		"limitation": "자생 가능성과 7세기 상업 생산량은 다름. 한국만의 독점 자생으로 설정하지 않음.",
		"url": "https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:91472-1",
		"kind": "modern_geography",
		"independently_verified": false,
		"workbook_range": "출처!A8:G8",
	},
	"S05": {
		"institution": "UNESCO 세계유산센터",
		"title": "Uvs Nuur Basin",
		"period": "현대 지리·생태 설명",
		"workbook_summary": "몽골·투바의 염호 환경을 확인할 수 있음.",
		"limitation": "7세기 식염 채취·수출 증거가 아님. 유목 전체 소금 풍부/전무 판정 모두 금지.",
		"url": "https://whc.unesco.org/en/list/769/",
		"kind": "modern_geography",
		"independently_verified": false,
		"workbook_range": "출처!A9:G9",
	},
	"S06": {
		"institution": "The Metropolitan Museum of Art",
		"title": "Internationalism in the Tang Dynasty",
		"period": "당 618~907년 전반",
		"workbook_summary": "말을 공급하는 튀르크 세력과 비단의 교환·외교적 관계를 설명.",
		"limitation": "당 전기간 서술이므로 660년 특정 부족·도시의 수량은 확정 불가.",
		"url": "https://www.metmuseum.org/essays/internationalism-in-the-tang-dynasty-618-906",
		"kind": "historical_reference",
		"independently_verified": false,
		"workbook_range": "출처!A10:G10",
	},
	"S07": {
		"institution": "국립중앙박물관",
		"title": "고창 봉덕리 1호분 출토 금동신발",
		"period": "5세기 백제 / 당서 인용",
		"workbook_summary": "백제 고급 직물과 가죽 복식 사용을 뒷받침.",
		"limitation": "사용·출토 사실이지 고창의 비단 생산지나 구리 광산 증거는 아님.",
		"url": "https://www.museum.go.kr/MUSEUM/contents/M0501000000.do?pageSize=10&relicRecommendCategory=&relicRecommendId=2351288&sc=&schM=view&sv=",
		"kind": "historical_reference",
		"independently_verified": false,
		"workbook_range": "출처!A11:G11",
	},
	"S08": {
		"institution": "국가유산청",
		"title": "백제 금동대향로",
		"period": "백제",
		"workbook_summary": "부여 능산리 출토 금동 공예품의 근거.",
		"limitation": "구리 광산 산지·대량 수출을 증명하지 않음. 주석·금 등은 게임에서 보조재로 추상화.",
		"url": "https://www.heritage.go.kr/heri/cul/culSelectDetail.do?VdkVgwKey=11%2C02870000%2C34&pageNo=1_1_1_0",
		"kind": "historical_reference",
		"independently_verified": false,
		"workbook_range": "출처!A12:G12",
	},
	"S09": {
		"institution": "국립경주박물관",
		"title": "삼국의 말 갑옷 특별전",
		"period": "삼국",
		"workbook_summary": "신라·가야·백제 출토 말 갑옷과 고구려 벽화 소개.",
		"limitation": "생산량·전투력 수치나 모든 병사의 보급률은 알 수 없음.",
		"url": "https://gyeongju.museum.go.kr/kor/html/sub02/0202.html?d_mng_no=170&mode=VD",
		"kind": "historical_reference",
		"independently_verified": false,
		"workbook_range": "출처!A13:G13",
	},
	"S10": {
		"institution": "국사편찬위원회",
		"title": "고구려의 농업",
		"period": "고구려",
		"workbook_summary": "고구려의 농업 기반과 평양·황해 일대 농업 설명.",
		"limitation": "고구려를 수렵·유목만으로 운영하는 설정을 피함. 정확한 도시 생산량은 설계값.",
		"url": "https://contents.history.go.kr/mobile/nh/view.do?levelId=nh_005_0050_0030_0030_0010",
		"kind": "historical_reference",
		"independently_verified": false,
		"workbook_range": "출처!A14:G14",
	},
	"S11": {
		"institution": "국가유산청",
		"title": "제주의 제주마",
		"period": "현대 품종 설명 / 1276년 기록",
		"workbook_summary": "몽고말 도입의 1276년 기록 소개.",
		"limitation": "탐라에 7세기 몽골식 대규모 군마장을 소급 배치하지 않음. 당시 말의 부재를 뜻하지도 않음.",
		"url": "https://www.heritage.go.kr/heri/cul/culSelectDetail.do?ccbaCpno=1363903470000",
		"kind": "later_period_context",
		"independently_verified": false,
		"workbook_range": "출처!A15:G15",
	},
	"S12": {
		"institution": "국사편찬위원회",
		"title": "삼국시대 중·후반기 밭농사 체계",
		"period": "삼국 중·후반 / 후대 비교 포함",
		"workbook_summary": "보리·콩·밀·조 등 곡물의 문헌·고고 자료를 소개.",
		"limitation": "곡물 통합은 게임 단순화. 실제 작물별 파종·수확기를 같다고 주장하지 않음.",
		"url": "https://contents.history.go.kr/front/km/print.do?levelId=km_027_0030_0020_0020&whereStr=",
		"kind": "historical_reference",
		"independently_verified": false,
		"workbook_range": "출처!A16:G16",
	},
	"S13": {
		"institution": "국립중앙박물관",
		"title": "가야실 상설전시",
		"period": "가야",
		"workbook_summary": "철·갑옷·큰칼·토기 등 고고 자료와 교역 소개.",
		"limitation": "가야의 정치적 존속과 지역 생산 기반을 구분. 7세기 생산 지속은 별도 검토.",
		"url": "https://vcm.museum.go.kr/MUSEUM/contents/M0201030700.do?schM=list&showHallId=760&showroomCode=DM0007",
		"kind": "historical_reference",
		"independently_verified": false,
		"workbook_range": "출처!A17:G17",
	},
	"D01": {
		"institution": "삼한660 사용자 합의·설계 제안",
		"title": "게임 요구사항",
		"period": "현재 대화",
		"workbook_summary": "1턴=1개월, 기존 군량경제 보존, 외교 협정·기술·시설·재료를 생산무역과 연결.",
		"limitation": "품목 수·가격·레시피·효과 계수·자동화 한도는 고증이 아닌 제안. 최종 확정 전.",
		"url": "현재 대화 / 외부 URL 없음",
		"kind": "design_proposal",
		"independently_verified": false,
		"workbook_range": "출처!A18:G18",
	},
}
const ITEMS: Dictionary = {
	"grain": {
		"id": "grain",
		"catalog_id": "grain",
		"name": "곡물·군량",
		"group_name": "곡물·군량",
		"category": "staple",
		"tier": "core",
		"enabled": true,
		"production_method": "regional_production",
		"production_condition": "기존 농업·수확",
		"economic_use": "도시 유지·잉여 군량 수출",
		"military_use": "기존 주둔군 소비",
		"abstraction": "쌀·조·보리 등 통합",
		"source_ids": ["S10","S12"],
		"existence_evidence": {"source_ids":["S10","S12"],"status":"workbook_reference","limitation":"기존 food_stock 한 장부 사용; 별도 곡물 중복 생성 금지"},
		"regional_evidence": [{"region":"평양·대동강·황해","evidence_type":"지역 범위 근거","summary":"고구려 농업 기반 설명","source_ids":["S10"],"limitation":"기존 농업 값 유지; 생산량 고증치 아님","workbook_range":"지역고증!A5:I5"},{"region":"한반도 농업 적지","evidence_type":"품목 근거","summary":"삼국 곡물 재배 근거","source_ids":["S12"],"limitation":"작물별 SKU는 통합, 모든 지형 동일 생산 금지","workbook_range":"지역고증!A6:I6"}],
		"regional_placement_confirmed": false,
		"storage": "province_food_stock",
		"recipe_ids": [],
		"workbook_range": "품목목록!A5:L5",
	},
	"salt": {
		"id": "salt",
		"catalog_id": "salt",
		"name": "소금",
		"group_name": "소금",
		"category": "basic_material",
		"tier": "core",
		"enabled": true,
		"production_method": "regional_processing",
		"production_condition": "검증된 염원·제염시설",
		"economic_use": "생활 수요·식품 보존",
		"military_use": "향후 보급 보존재",
		"abstraction": "자염 등 생산법은 시설 속성",
		"source_ids": ["S02","S05"],
		"existence_evidence": {"source_ids":["S02"],"status":"workbook_reference","limitation":"해안이면 자동 생산 금지; 염호 존재만으로 식용 소금 생산 확정 금지"},
		"regional_evidence": [{"region":"한반도 연해","evidence_type":"품목 근거","summary":"삼국 소금 생산·거래 기록","source_ids":["S02"],"limitation":"역사적 염원·제염 방식·시설 입지 확인 후 활성","workbook_range":"지역고증!A11:I11"},{"region":"몽골·투바 염호권","evidence_type":"지리 근거만","summary":"Uvs Nuur 염호 환경","source_ids":["S05"],"limitation":"염호는 채염·식염 유통 증거가 아님; 유목 전체 일괄배치 금지","workbook_range":"지역고증!A12:I12"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A6:L6",
	},
	"iron": {
		"id": "iron",
		"catalog_id": "iron",
		"name": "철",
		"group_name": "철",
		"category": "basic_material",
		"tier": "core",
		"enabled": true,
		"production_method": "regional_processing",
		"production_condition": "확정된 지역 공급 허용·기본 제련 기술·제철시설",
		"economic_use": "소재 수출·군수산업",
		"military_use": "무기·갑옷의 투입재",
		"abstraction": "철광석·목탄은 자원/운영비로 추상화",
		"source_ids": ["S01"],
		"existence_evidence": {"source_ids":["S01"],"status":"workbook_reference","limitation":"매장·제련·출토를 분리; 철도 제련을 거쳐야 함"},
		"regional_evidence": [{"region":"경주 황성동 일대","evidence_type":"제철 근거","summary":"제철유적 소개","source_ids":["S01"],"limitation":"도시 폴리곤·유적 연대와 7세기 지속 검토 필요","workbook_range":"지역고증!A7:I7"},{"region":"김해·부산 일대","evidence_type":"유통/출토 근거","summary":"철정 유통·출토 집중","source_ids":["S01"],"limitation":"출토량을 광산량으로 바꾸지 않음; 정치세력과 생산지 분리","workbook_range":"지역고증!A8:I8"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": ["iron_supply"],
		"workbook_range": "품목목록!A7:L7",
	},
	"copper": {
		"id": "copper",
		"catalog_id": "copper",
		"name": "구리",
		"group_name": "구리",
		"category": "basic_material",
		"tier": "core",
		"enabled": true,
		"production_method": "regional_processing",
		"production_condition": "검증된 광산·제련시설",
		"economic_use": "공예산업 소재",
		"military_use": "직접 전투력 보너스 없음",
		"abstraction": "주석·금박은 보조재 비용 처리",
		"source_ids": ["S08"],
		"existence_evidence": {"source_ids":["S08"],"status":"workbook_reference","limitation":"금동 유물은 구리 광산 증거 아님; 산지 확인 전 자연생산 잠금"},
		"regional_evidence": [{"region":"한반도·중국 광산 후보","evidence_type":"미확인","summary":"이번 조사에서 7세기 개별 광산 근거 미확보","source_ids":["S08"],"limitation":"현대 광산 지도만으로 초기 광산 생성 금지","workbook_range":"지역고증!A9:I9"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A8:L8",
	},
	"timber": {
		"id": "timber",
		"catalog_id": "timber",
		"name": "목재",
		"group_name": "목재",
		"category": "raw_resource",
		"tier": "core",
		"enabled": true,
		"production_method": "regional_production",
		"production_condition": "임산 자원·벌목/건조시설",
		"economic_use": "건설·조선·제조 소재",
		"military_use": "무기 부재·향후 수송선",
		"abstraction": "수종별 별도 재고 없음",
		"source_ids": ["S01"],
		"existence_evidence": {"source_ids":["S01"],"status":"indirect_reference","limitation":"목탄 수요는 간접 근거; 도시별 산림량은 미검증"},
		"regional_evidence": [{"region":"산림권","evidence_type":"간접 근거","summary":"제철 연료 필요성의 간접 근거","source_ids":["S01"],"limitation":"산림 환경·운송 접근성 별도 조사 필요","workbook_range":"지역고증!A21:I21"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A9:L9",
	},
	"horses": {
		"id": "horses",
		"catalog_id": "horses",
		"name": "군마",
		"group_name": "군마",
		"category": "livestock",
		"tier": "core",
		"enabled": true,
		"production_method": "regional_production",
		"production_condition": "목초지·사육 기반·조련",
		"economic_use": "고가 전략 수출",
		"military_use": "기병 편성·전손 보충",
		"abstraction": "품질은 속성; 품종 SKU 분리 없음",
		"source_ids": ["S06","S11"],
		"existence_evidence": {"source_ids":["S06"],"status":"workbook_reference","limitation":"모든 말이 즉시 군마가 아님; 번식은 장기, 월 산출은 사육기반 추상화"},
		"regional_evidence": [{"region":"튀르크·초원 사육권","evidence_type":"시대 범위 근거","summary":"당과 말·비단 교환 서술","source_ids":["S06"],"limitation":"632/642/660/663/670별 공급 세력·사육지 추가 조사","workbook_range":"지역고증!A15:I15"},{"region":"탐라","evidence_type":"후대 자료","summary":"1276년 몽고말 도입 기록","source_ids":["S11"],"limitation":"7세기 말이 없었다는 뜻은 아님; 대규모 몽골 목장 적용 금지","workbook_range":"지역고증!A16:I16"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A10:L10",
	},
	"leather": {
		"id": "leather",
		"catalog_id": "leather",
		"name": "가죽",
		"group_name": "가죽",
		"category": "basic_material",
		"tier": "core",
		"enabled": true,
		"production_method": "regional_processing",
		"production_condition": "목축/수렵 기반·무두질",
		"economic_use": "갑옷·생활 제조 소재",
		"military_use": "갑옷 제작·장구류",
		"abstraction": "원피·소가죽 등 통합",
		"source_ids": ["S07","S09"],
		"existence_evidence": {"source_ids":["S07","S09"],"status":"workbook_reference","limitation":"고급 모피와 별도; 같은 사냥량에서 가죽·모피 이중 지급 금지"},
		"regional_evidence": [{"region":"목축·수렵 공급권","evidence_type":"사용 근거","summary":"가죽 복식 및 갑옷 문화","source_ids":["S07","S09"],"limitation":"목축 공급량·무두질 입지는 미확정","workbook_range":"지역고증!A19:I19"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A11:L11",
	},
	"cloth": {
		"id": "cloth",
		"catalog_id": "cloth",
		"name": "일반 직물",
		"group_name": "일반 직물",
		"category": "manufactured_good",
		"tier": "core",
		"enabled": true,
		"production_method": "manufacturing",
		"production_condition": "섬유작물 기반·직조",
		"economic_use": "생활 수요·군복",
		"military_use": "피복 보급",
		"abstraction": "삼베·모시 등; 면직물 대량 보급 제외",
		"source_ids": ["S03"],
		"existence_evidence": {"source_ids":["S03"],"status":"workbook_reference","limitation":"섬유 원료는 자원 태그; 양잠과 구분"},
		"regional_evidence": [{"region":"삼국 직조권","evidence_type":"품목 근거","summary":"마직물 수출 기록","source_ids":["S03"],"limitation":"지역 섬유작물·직조시설은 후속 근거 확인","workbook_range":"지역고증!A18:I18"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A12:L12",
	},
	"silk": {
		"id": "silk",
		"catalog_id": "silk",
		"name": "비단",
		"group_name": "비단",
		"category": "manufactured_good",
		"tier": "core",
		"enabled": true,
		"production_method": "manufacturing",
		"production_condition": "양잠 기반·견직 기술",
		"economic_use": "상류층 수요·고가 수출",
		"military_use": "외교 교환재; 공격력 없음",
		"abstraction": "여러 견직물 통합",
		"source_ids": ["S06","S07"],
		"existence_evidence": {"source_ids":["S06","S07"],"status":"workbook_reference","limitation":"일반 직물에서 변환 금지; 출토만으로 양잠 산지 확정 금지"},
		"regional_evidence": [{"region":"당·백제 등 직물 문화권","evidence_type":"유통/사용 근거","summary":"교환·고급 직물 사용","source_ids":["S06","S07"],"limitation":"사용·부장만으로 양잠 생산지 지정 금지","workbook_range":"지역고증!A17:I17"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A13:L13",
	},
	"sword": {
		"id": "sword",
		"catalog_id": "weapons",
		"name": "무기 (칼)",
		"group_name": "무기",
		"category": "manufactured_good",
		"tier": "core",
		"enabled": true,
		"production_method": "manufacturing",
		"production_condition": "철·목재·단조시설",
		"economic_use": "가공 부가가치·전략 수출",
		"military_use": "부대 장비 충족률",
		"abstraction": "칼·창·활 계열 통합, 병종 기술로 차별",
		"source_ids": ["S01","S13"],
		"existence_evidence": {"source_ids":["S01","S13"],"status":"workbook_reference","limitation":"추상 레시피는 모든 활이 철제라는 뜻 아님; 개인 보물과 별개"},
		"regional_evidence": [{"region":"신라·백제·고구려 및 옛 가야권","evidence_type":"제품 존재 근거","summary":"철기·갑주 유물과 벽화","source_ids":["S01","S09"],"limitation":"유물 종류가 도시 전체 군수 생산량을 뜻하지 않음","workbook_range":"지역고증!A20:I20"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": ["iron_sword"],
		"workbook_range": "품목목록!A14:L14",
	},
	"armor": {
		"id": "armor",
		"catalog_id": "armor",
		"name": "갑옷",
		"group_name": "갑옷",
		"category": "manufactured_good",
		"tier": "core",
		"enabled": true,
		"production_method": "manufacturing",
		"production_condition": "철·가죽·갑주시설",
		"economic_use": "고부가 군수품",
		"military_use": "중장 보병·중장기병 편성",
		"abstraction": "보병갑·마갑은 장비 등급/소모량으로 구분",
		"source_ids": ["S09"],
		"existence_evidence": {"source_ids":["S09"],"status":"workbook_reference","limitation":"단순 보유만으로 전군 방어력 상승 금지"},
		"regional_evidence": [{"region":"신라·백제·고구려 및 옛 가야권","evidence_type":"제품 존재 근거","summary":"철기·갑주 유물과 벽화","source_ids":["S01","S09"],"limitation":"유물 종류가 도시 전체 군수 생산량을 뜻하지 않음","workbook_range":"지역고증!A20:I20"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A15:L15",
	},
	"ginseng": {
		"id": "ginseng",
		"catalog_id": "ginseng",
		"name": "인삼",
		"group_name": "인삼",
		"category": "regional_specialty",
		"tier": "core",
		"enabled": true,
		"production_method": "gathering",
		"production_condition": "검증된 자생환경·채집",
		"economic_use": "희소 고가 수출",
		"military_use": "직접 전투력·치료 보너스 없음",
		"abstraction": "일반 약재 전체와 섞지 않음",
		"source_ids": ["S03","S04"],
		"existence_evidence": {"source_ids":["S03"],"status":"workbook_reference","limitation":"한국 독점 자생으로 설정 금지; 현대 재배단지 소급 금지"},
		"regional_evidence": [{"region":"한반도·동북아 온대 산림","evidence_type":"지리+품목 근거","summary":"자생 범위와 삼국 수출품 기록","source_ids":["S04","S03"],"limitation":"한국 독점 자생 금지; 특정 도시·수량은 미확정","workbook_range":"지역고증!A13:I13"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A16:L16",
	},
	"furs": {
		"id": "furs",
		"catalog_id": "furs",
		"name": "모피",
		"group_name": "모피",
		"category": "regional_specialty",
		"tier": "core",
		"enabled": true,
		"production_method": "gathering",
		"production_condition": "수렵환경·선별 가공",
		"economic_use": "귀족 수요·고가 교역",
		"military_use": "추후 방한 장비; 초기 효과 없음",
		"abstraction": "담비 등은 지역 품질 태그",
		"source_ids": ["S03"],
		"existence_evidence": {"source_ids":["S03"],"status":"workbook_reference","limitation":"모든 초원 일괄 대량생산 금지; 종·산지 후속 조사"},
		"regional_evidence": [{"region":"북방 산림·수렵권","evidence_type":"품목 근거","summary":"삼국 수출품 기록","source_ids":["S03"],"limitation":"단순 북쪽/유목 태그만으로 대량생산하지 않음","workbook_range":"지역고증!A14:I14"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A17:L17",
	},
	"metalcraft": {
		"id": "metalcraft",
		"catalog_id": "metalcraft",
		"name": "금속 공예품",
		"group_name": "금속 공예품",
		"category": "manufactured_good",
		"tier": "core",
		"enabled": true,
		"production_method": "manufacturing",
		"production_condition": "구리·금공 기술·공방",
		"economic_use": "문화도시의 고가 수출",
		"military_use": "외교 선물; 전투력 없음",
		"abstraction": "장식구·금동 공예품 통합",
		"source_ids": ["S08","S03"],
		"existence_evidence": {"source_ids":["S08","S03"],"status":"workbook_reference","limitation":"합금·도금 보조재 추상화; 화폐 금과 실제 금광은 별개"},
		"regional_evidence": [{"region":"부여 능산리","evidence_type":"제조문화 근거","summary":"백제 금동대향로 출토","source_ids":["S08"],"limitation":"출토는 현지 광산·대량 수출 증거 아님","workbook_range":"지역고증!A10:I10"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A18:L18",
	},
	"preserved_food": {
		"id": "preserved_food",
		"catalog_id": "preserved_food",
		"name": "가공식품",
		"group_name": "가공식품",
		"category": "manufactured_good",
		"tier": "expansion",
		"enabled": false,
		"production_method": "manufacturing",
		"production_condition": "곡물 등 식재·소금·식품공방",
		"economic_use": "식품 부가가치",
		"military_use": "향후 원정 보급",
		"abstraction": "간장·장류·건조식품은 용도 확인 후 통합",
		"source_ids": ["D01"],
		"existence_evidence": {"source_ids":["D01"],"status":"design_only","limitation":"간장은 설계 예시; 정확한 7세기 명칭·생산과 보급 효능 검증 필요"},
		"regional_evidence": [{"region":"미정","evidence_type":"미확인","summary":"이번 범위에서 개별 생산·교역 근거 미확보","source_ids":["D01"],"limitation":"설계 후보이며 역사 배치로 사용 금지","workbook_range":"지역고증!A22:I22"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A19:L19",
	},
	"pottery": {
		"id": "pottery",
		"catalog_id": "pottery",
		"name": "토기",
		"group_name": "토기",
		"category": "manufactured_good",
		"tier": "expansion",
		"enabled": false,
		"production_method": "manufacturing",
		"production_condition": "점토 기반·가마",
		"economic_use": "생활·포장 수요",
		"military_use": "직접 군사효과 없음",
		"abstraction": "도기·토기 통합; 고려청자 금지",
		"source_ids": ["S13"],
		"existence_evidence": {"source_ids":["S13"],"status":"workbook_reference","limitation":"포장비에 포함 가능; 단독 선택의 의미가 있을 때만 추가"},
		"regional_evidence": [{"region":"옛 가야권 등","evidence_type":"제품 존재 근거","summary":"가야 토기 전시자료","source_ids":["S13"],"limitation":"7세기 생산지 지속·실제 수출 수요 추가 조사","workbook_range":"지역고증!A23:I23"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A20:L20",
	},
	"lacquerware": {
		"id": "lacquerware",
		"catalog_id": "lacquerware",
		"name": "칠기",
		"group_name": "칠기",
		"category": "manufactured_good",
		"tier": "expansion",
		"enabled": false,
		"production_method": "manufacturing",
		"production_condition": "옻 자원·목재·칠공방",
		"economic_use": "고급 공예·수출",
		"military_use": "초기 군사효과 없음",
		"abstraction": "금속공예와 소비 역할 중복 검토",
		"source_ids": ["D01"],
		"existence_evidence": {"source_ids":["D01"],"status":"design_only","limitation":"이번 조사에서 지역·시기 근거 미확보; 적용 보류"},
		"regional_evidence": [{"region":"미정","evidence_type":"미확인","summary":"이번 범위에서 개별 생산·교역 근거 미확보","source_ids":["D01"],"limitation":"설계 후보이며 역사 배치로 사용 금지","workbook_range":"지역고증!A22:I22"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A21:L21",
	},
	"tea": {
		"id": "tea",
		"catalog_id": "tea",
		"name": "차",
		"group_name": "차",
		"category": "regional_specialty",
		"tier": "expansion",
		"enabled": false,
		"production_method": "regional_processing",
		"production_condition": "차나무 적지·제다",
		"economic_use": "지역별 기호품 수요",
		"military_use": "군사효과 없음",
		"abstraction": "약재와 별도이나 초기 미도입",
		"source_ids": ["D01"],
		"existence_evidence": {"source_ids":["D01"],"status":"design_only","limitation":"후대 차마무역·차문화 소급 금지; 7세기 생산교역 조사 후 판단"},
		"regional_evidence": [{"region":"미정","evidence_type":"미확인","summary":"이번 범위에서 개별 생산·교역 근거 미확보","source_ids":["D01"],"limitation":"설계 후보이며 역사 배치로 사용 금지","workbook_range":"지역고증!A22:I22"}],
		"regional_placement_confirmed": false,
		"storage": "city_inventory",
		"recipe_ids": [],
		"workbook_range": "품목목록!A22:L22",
	},
}
const SWORD_TECHNOLOGY: Dictionary = {
	"name": "도검 제작", "max_level": 1, "base_gold": 200, "base_turns": 1,
	"effect": "군기감에서 철을 소비해 칼 생산 (검증용 임시 설정)",
}
const SMELTING_TECHNOLOGY: Dictionary = {
	"name": "기본 제련", "max_level": 1, "researchable": false,
	"base_gold": 0, "base_turns": 0,
	"effect": "시작 시나리오의 설계에 따라 보유하는 기본 기술 (연구로 획득 불가)",
}
const SMELTER_FACILITY: Dictionary = {
	"name": "제철시설", "max_level": 1, "base_gold": 240, "base_turns": 2,
	"effect": "지역 공급 허용 시 철 공급. 군대 능력치 효과 없음 (임시 밸런스)",
}
# Explicit order within each city; never depend on dictionary insertion order.
const RECIPE_ORDER: Array[String] = ["iron_supply", "iron_sword"]
const RECIPES: Dictionary = {
	"iron_supply": {
		"enabled": true, "name": "철 공급", "regional_supply": true,
		"research": {"basic_smelting": 1}, "buildings": {"smelter": 1},
		"inputs": {}, "outputs": {"iron": 2}, "operating_gold": 6,
	},
	"iron_sword": {
		"enabled": true,
		"name": "철로 칼 제작", "research": {"swordsmithing": 1},
		"buildings": {"forge": 1}, "inputs": {"iron": 2},
		"outputs": {"sword": 1}, "operating_gold": 10,
	},
}


static func canonical_item_id(item_id: String) -> String:
	return str(ITEM_ALIASES.get(item_id, item_id))


static func recipe_is_enabled(recipe_id: String) -> bool:
	if not RECIPES.has(recipe_id) or not bool(RECIPES[recipe_id].get("enabled", false)):
		return false
	var recipe: Dictionary = RECIPES[recipe_id]
	for part: String in ["inputs", "outputs"]:
		for item_id: String in recipe[part]:
			if not ITEMS.has(item_id) or not bool(ITEMS[item_id]["enabled"]):
				return false
			# 기존 군량 경제와 별개의 제조만 허용. grain 투입/산출은 후속 구현 대상입니다.
			if str(ITEMS[item_id]["storage"]) != "city_inventory":
				return false
	return true
